// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRk0lq2mf_Y0sciAWVGpIxQeqI_Nr5Io4',
    appId: '1:131987594270:web:364b4e2e68420a9c00220f',
    messagingSenderId: '131987594270',
    projectId: 'fir-todo-1b6de',
    authDomain: 'fir-todo-1b6de.firebaseapp.com',
    storageBucket: 'fir-todo-1b6de.firebasestorage.app',
    measurementId: 'G-FG03HFYYY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByA5omcIgVucINjXZP249oh2hLoVBgYig',
    appId: '1:131987594270:android:2097196295b0fcaf00220f',
    messagingSenderId: '131987594270',
    projectId: 'fir-todo-1b6de',
    storageBucket: 'fir-todo-1b6de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArCgep_BUIqu_4QcGtyINNPPdOvwtCHOo',
    appId: '1:131987594270:ios:a14bbdb4c10d02bd00220f',
    messagingSenderId: '131987594270',
    projectId: 'fir-todo-1b6de',
    storageBucket: 'fir-todo-1b6de.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArCgep_BUIqu_4QcGtyINNPPdOvwtCHOo',
    appId: '1:131987594270:ios:a14bbdb4c10d02bd00220f',
    messagingSenderId: '131987594270',
    projectId: 'fir-todo-1b6de',
    storageBucket: 'fir-todo-1b6de.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTester',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRk0lq2mf_Y0sciAWVGpIxQeqI_Nr5Io4',
    appId: '1:131987594270:web:fce61f4d58c67e2200220f',
    messagingSenderId: '131987594270',
    projectId: 'fir-todo-1b6de',
    authDomain: 'fir-todo-1b6de.firebaseapp.com',
    storageBucket: 'fir-todo-1b6de.firebasestorage.app',
    measurementId: 'G-Z8QKJPFPDR',
  );
}
